### ISSUE TITLE
Problems with VM create

### ISSUE THREAD

**Issue by idofl** [azure-contrib/azure-scripty#10]
I'm trying to run the following code to create a VM, similar to how I use the "azure vm create" CLI (for a Windows Server 2012 image).

cmd = {
 command: 'vm create',
 positional: [vmName, imageName, 'administrator', password],
 location: location,  
 rdp: true
};
scripty.invoke(cmd)

The scripts runs for a second or two and then prints:
Error: Command failed: The hosted service is not valid.

If I run the azure cli "vm create" command with the same values (positional and parameters) it works without a problem (the CLI creates a cloud service for the VM).

Any ideas what is wrong with this code?

**Comment by glennblock** [comment]
@idfol it is probably because scripty is currently pinned to an early version of the CLI. I am about to change this and will test your command to make sure it works.

**Comment by glennblock** [comment]
@idofl fixed now, sorry for the delay!
