### ISSUE TITLE
bug with error callbacks

### ISSUE THREAD

**Issue by ysxu** [azure-contrib/azure-scripty#12]
Hi Glenn,

Right now if a user forgets to add a space between commands.

scripty.invoke('mobile table createservicename', function (err, results) {
    console.log(err);
        console.log(results);
}

gives err=undefined and results=null.

I tried some other random gibberish commands and it seems like invoke doesn't callback error that Azure CLI runs into. 

Thanks!
-Mimi :)

**Comment by glennblock** [comment]
This is fixed now @ysxu! Thanks for reporting it!

If you run this code

``` javascript
scripty.invoke('mobile table createservicename', function (err, results) {
  console.log(err);
});
```

you will get this output (the err object will have the error from the cli)

```
error:   'createservicename' is not an azure command. See 'azure help'.
```

which is probably what you'd expect :-) 

This fixes a long standing bug which turned out to be way easier to fix than I had thought.
