### ISSUE TITLE
Results are wrapped in an extra array

### ISSUE THREAD

**Issue by joshtwist** [azure-contrib/azure-scripty#4]
var cli = require('azure-scripty');
var servicename = 'mymobileservice';

cli.invoke({
command: 'mobile table list',
positional: [servicename]
}, function(err, results) {
console.log(results);
// results is an array in an array
});

Results come back in an additional array

**Comment by glennblock** [comment]
The array is currently by design, because if there are multiple commands, then you get passed all of the results passed hence the array. For consistency I kept it as an array even if it is a single command. Do you think it should not be an array of 1, and instead should be single item?

**Comment by joshtwist** [comment]
Personally I think single is the way to go:
- not intuitive to have to unbundle an extra array for single command
- people more likely to use single command when trying your library 
- not sure of value of multiple commands in current implementation; i believe it runs these sequentially. If I want to run commands sequentially then there's a very good chance that I want to use result from 1 in command 2 which is hard at present.
