### ISSUE TITLE
Allow passing "false" as the value for flags.

### ISSUE THREAD

**Issue by glennblock** [azure-contrib/azure-scripty#7]

**Comment by glennblock** [comment]
@paulbatum you wanted this. You can now pass null, false or empty string.

**Comment by paulbatum** [comment]
Hang on, why would I pass false? I want to pass true. The equivalent of --git should be { git: true }

**Comment by glennblock** [comment]
oops :-)

**Comment by glennblock** [comment]
OK fixed now @paultbatum.
